# Generated by Django 4.2.2 on 2023-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_projects_technologies_projects_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
